### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pawantiwarii** [Noob-214/Logan_Ysl#3]
make[1]: Entering directory '/home/pawan/Downloads/kernel/Logan_Ysl-Stable/out'
  GEN     ./Makefile
scripts/kconfig/conf  --silentoldconfig Kconfig
drivers/input/touchscreen/ft5446/Kconfig:5:warning: ignoring type redefinition of 'TOUCHSCREEN_FT5446' from 'tristate' to 'boolean'
warning: (USB_CI13XXX_MSM) selects USB_MSM_OTG which has unmet direct dependencies (USB_SUPPORT && (USB || USB_GADGET) && (ARCH_QCOM || COMPILE_TEST))
warning: (USB_CI13XXX_MSM) selects USB_MSM_OTG which has unmet direct dependencies (USB_SUPPORT && (USB || USB_GADGET) && (ARCH_QCOM || COMPILE_TEST))
  SYSTBL  arch/x86/entry/syscalls/../../include/generated/asm/syscalls_32.h
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/asm/unistd_32_ia32.h
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/asm/unistd_64_x32.h
  HOSTCC  scripts/basic/fixdep
  SYSTBL  arch/x86/entry/syscalls/../../include/generated/asm/syscalls_64.h
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/uapi/asm/unistd_32.h
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/uapi/asm/unistd_64.h
  SYSHDR  arch/x86/entry/syscalls/../../include/generated/uapi/asm/unistd_x32.h
  CHK     include/config/kernel.release
  HOSTCC  scripts/basic/bin2c
  GEN     ./Makefile
  WRAP    arch/x86/include/generated/asm/clkdev.h
  WRAP    arch/x86/include/generated/asm/cputime.h
  WRAP    arch/x86/include/generated/asm/dma-contiguous.h
  WRAP    arch/x86/include/generated/asm/early_ioremap.h
  WRAP    arch/x86/include/generated/asm/mcs_spinlock.h
  WRAP    arch/x86/include/generated/asm/mm-arch-hooks.h
  CHK     include/generated/uapi/linux/version.h
  UPD     include/generated/uapi/linux/version.h
  HOSTCC  scripts/genksyms/genksyms.o
  UPD     include/config/kernel.release
  SHIPPED scripts/genksyms/parse.tab.c
  SHIPPED scripts/genksyms/lex.lex.c
  SHIPPED scripts/genksyms/keywords.hash.c
  SHIPPED scripts/genksyms/parse.tab.h
  HOSTCC  scripts/genksyms/parse.tab.o
  HOSTCC  scripts/genksyms/lex.lex.o
  CC      scripts/mod/empty.o
clang-13: warning: argument unused during compilation: '-mno-sse' [-Wunused-command-line-argument]
clang-13: warning: argument unused during compilation: '-mno-mmx' [-Wunused-command-line-argument]
clang-13: warning: argument unused during compilation: '-mno-sse2' [-Wunused-command-line-argument]
clang-13: warning: argument unused during compilation: '-mno-3dnow' [-Wunused-command-line-argument]
fatal error: error in backend: Only small, tiny and large code models are allowed on AArch64
clang-13: error: clang frontend command failed with exit code 70 (use -v to see invocation)
Proton clang version 13.0.0 (https://github.com/llvm/llvm-project 30df6d5d6a8537d3ec7d8fe4299289a4c5a74d5c)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/pawan/Downloads/toolchain/proton-clang-master/bin
clang-13: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-13: note: diagnostic msg: /tmp/empty-894199.c
clang-13: note: diagnostic msg: /tmp/empty-894199.sh
clang-13: note: diagnostic msg: 

********************
make[3]: *** [../scripts/Makefile.build:343: scripts/mod/empty.o] Error 70
make[2]: *** [../scripts/Makefile.build:656: scripts/mod] Error 2
make[2]: *** Waiting for unfinished jobs....
  HOSTLD  scripts/genksyms/genksyms
make[1]: *** [/home/pawan/Downloads/kernel/Logan_Ysl-Stable/Makefile:579: scripts] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/pawan/Downloads/kernel/Logan_Ysl-Stable/out'
make: *** [Makefile:152: sub-make] Error 2

**Comment by x0rzavi** [comment]
@100pawan

**Comment by Noob-214** [comment]
Fixed 
Now you can compile.

**Comment by pawantiwarii** [comment]
oky

pawan tiwari
