### ISSUE TITLE
error in 266

### ISSUE THREAD

**Issue by pawantiwarii** [Noob-214/Logan_Ysl#6]
make[1]: Entering directory '/home/pawan_tiwari/Downloads/kernel/Logan_Ysl-Stable/out'
arch/arm64/Makefile:27: ld does not support --fix-cortex-a53-843419; kernel may be susceptible to erratum
../scripts/gcc-version.sh: line 25: clang: command not found
../scripts/gcc-version.sh: line 26: clang: command not found
../scripts/gcc-version.sh: line 25: clang: command not found
../scripts/gcc-version.sh: line 26: clang: command not found
make[1]: clang: No such file or directory
make[1]: clang: No such file or directory
  CHK     include/config/kernel.release
make[1]: clang: No such file or directory
  Using .. as source for kernel
make[1]: clang: No such file or directory
  GEN     ./Makefile
make[1]: clang: No such file or directory
make[1]: clang: No such file or directory
  CHK     include/generated/uapi/linux/version.h
make[1]: clang: No such file or directory
  CHK     include/generated/utsrelease.h
make[1]: clang: No such file or directory
make[1]: clang: No such file or directory
make[1]: clang: No such file or directory
  CC      kernel/bounds.s
/bin/sh: 1: clang: not found
make[2]: *** [.././Kbuild:21: kernel/bounds.s] Error 127
make[1]: *** [/home/pawan_tiwari/Downloads/kernel/Logan_Ysl-Stable/Makefile:1176: prepare0] Error 2
make[1]: Leaving directory '/home/pawan_tiwari/Downloads/kernel/Logan_Ysl-Stable/out'
make: *** [Makefile:152: sub-make] Error 2

**Comment by Noob-214** [comment]
@100pawan export clang path correctly

**Comment by pawantiwarii** [comment]
> @100pawan export clang path correctly

ohh its my mistake in typing

**Comment by Noob-214** [comment]
F
