### ISSUE TITLE
[HELP] Enabling kernel moduls

### ISSUE THREAD

**Issue by Mr-x2020** [Noob-214/Logan_Ysl#7]
There are features are not working in Nethunter and I have to enable them in the Android kernel source, I started to compile the kernel source of my device and I tried to enable BT_RFCOMM, HID, Injection, Nexmon features in menuconfig but I failed because I don't know what these features named in menuconfig there are too many options. I need help finding the path to BT_RFCOMM, HID, Injection, Nexmon features in menuconfig

**Comment by Noob-214** [comment]
ask here https://t.me/UggNethunTer214
